### ISSUE TITLE
Old speed ui looks rather strange 

### ISSUE THREAD

**Issue by Wladefant** [joschahenningsen/TUM-Live#1162] opened 2023-09-14 13:06 UTC
I like the UI very much looks modern to me and matches the tum theme. But somehow you missed the playback speed ui?
I am right now in the beta player 
![image](https://github.com/TUM-Dev/gocast/assets/79611093/9540776d-e88f-4ba7-803b-3c0afaad03b8)
The ui looks rather strange

**Comment by karjo24** [comment] 2024-11-14 11:24
Duplicate of #1165 (+ outdated screenshot?)

**Closed as not planned by karjo24** 2024-11-14 11:24 UTC
Labels: enhancement
