### ISSUE TITLE
Logged out when opening non-public VOD

### ISSUE THREAD

**Issue by PRehker** [joschahenningsen/TUM-Live#1339] opened 2024-03-20 08:13 UTC
**Describe the bug**
When clicking on a link of a VOD on the homepage, I get logged out.

**To Reproduce**
1. Go to live.rbg.tum.de
2. log in to see a non-public course
3. try to open an old VOD
4. See error 403 and login button at the top of the page.

**Expected behavior**
Instead of having to log back in, display the stream and stay logged in.

**Screenshots**
https://github.com/TUM-Dev/gocast/assets/105861512/25ea76a6-ec04-4c1e-bd5c-bed5469d1bce

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chromium
 - Version 122.0.6261.129

**Smartphone (please complete the following information):**
 - Device: MacBook Air M1
 - OS: macOS Sonoma 14.3.1
 - Browser: Arc
 - Version Chromium 122.0.6261.129

**Comment by YiranDuan721** [comment] 2024-03-24 16:42
Thanks for the issue. I tried using a non-admin account, reproduced the problem, but my login status is not changed if I go back to the last page, or visit any valid TUM-Live page. I think the more important problem here is that the private VoDs are still publicly listed (#1266).

Back to the issue itself, comments / ideas wanted here: Is it a problem to have no user information on the 403 page?

**Comment by karjo24** [comment] 2024-11-14 14:07
> Back to the issue itself, comments / ideas wanted here: Is it a problem to have no user information on the 403 page?

No information is no problem when the page that the user wants to access is not accessible in any "valid" way. Since the underlying issue of private vods listed on the course page is fixed (see  #1266), I'm gonna close this issue.

**Closed as completed by karjo24** 2024-11-14 14:07 UTC
Labels: priority:medium
