### ISSUE TITLE
Upcoming lectures order flipped

### ISSUE THREAD

**Issue by alexanderstephan** [joschahenningsen/TUM-Live#722] opened 2022-10-13 21:01 UTC
**Describe the bug**
The upcoming lecture section is sorted in way that the next lecture is at the bottom. As I student I would rather want to see when the next lecture takes place, so I would argue that we should sort this the other way around.

**To Reproduce**
1. Go to https://live.rbg.tum.de/course/2022/W/GBS

**Screenshots**
<img width="364" alt="grafik" src="https://user-images.githubusercontent.com/30267166/195709421-b000e1bb-e42a-448d-a6d3-d563e5505f72.png">

**Comment by joschahenningsen** [comment] 2022-10-14 09:15
Duplicate of #370

**Closed as completed by joschahenningsen** 2022-10-14 09:15 UTC
Labels: bug
