### ISSUE TITLE
Approving chat message does not remove “only visible to you” in Safari

### ISSUE THREAD

**Issue by Jojaa350** [joschahenningsen/TUM-Live#808] opened 2022-11-29 22:32 UTC
**Describe the bug**
Approving a chat message as an admin in Safari does work but not remove the “only visible to you” message.

**To Reproduce**
1. Be admin, use Safari, go to a lecture with moderation enabled
2. Have a student create a chat message
3. Approve said message

**Expected behavior**
This text should be removed.

**Desktop (please complete the following information):**
 - OS: MacOS (version unknown)
 - Safari 14.1.2

**Additional context**
I am not the owner of a mac and have only seen it on somebody else's MacBook and reporting it. Please someone verify that for me.

**Comment by MatthiasReumann** [comment] 2022-11-30 09:15
Locally I can't reproduce this error. [MacOS Ventura (13.0.1) on Safari Version 16.1]

Could you get in touch with the MacBook owner and ask him to re-verify the problem (Maybe this has already been fixed in a later deployment) and:
- Does the console print any error messages? 
- Does `cmd-option-e` (Clean Caches) in Safari solve the problem?

Thanks!

**Closed as completed** 2023-01-22 00:45 UTC
