### ISSUE TITLE
Hidden lectures shouldn't be shown to non-admins on the course page

### ISSUE THREAD

**Issue by joschahenningsen** [joschahenningsen/TUM-Live#1187] opened 2023-10-04 06:04 UTC
![image](https://github.com/TUM-Dev/gocast/assets/44805696/b39a0019-edde-4b6f-9c79-03e24e594e1f)

![image](https://github.com/TUM-Dev/gocast/assets/44805696/fbc40178-946f-4969-87aa-548f9b111bb9)

![image](https://github.com/TUM-Dev/gocast/assets/44805696/ab155b8e-420a-4106-b7c1-3e059d0ddf48)

**Comment by karjo24** [comment] 2024-11-14 13:00
Is this issue still up to date? I can't reproduce this and looking at the code, I don't see how this would happen.

**Comment by karjo24** [comment] 2024-11-14 13:28
Duplicate of #1266, which was fixed already.

**Closed as completed by karjo24** 2024-11-14 13:28 UTC
Labels: UI
