### ISSUE TITLE
Show transcript for lectures with subtitles

### ISSUE THREAD

**Issue by carlobortolan** [joschahenningsen/TUM-Live#1369] opened 2024-08-30 16:40 UTC
**Is your feature request related to a problem? Please describe.**
\-

**Describe the solution you'd like**
- Add the option to see a searchable transcript next to the lecture video if subtitles are available.
- Transcript should be synchronized with the current progress of the video (and, for example, also show the current video timestamp - see example screenshot from YouTube below).

**Describe alternatives you've considered**
Download option for transcripts as a text file.

**Additional context**
1. I'd work on this issue as part of the Open Source Lab

<details>
<summary>2. YouTube transcript function</summary>  

![image](https://github.com/user-attachments/assets/527c35e4-9655-48fb-aa32-bacffb410b9b)

</details>

**Comment by joschahenningsen** [comment] 2024-08-30 17:59
probably duplicate of #1364  :) 
Functionality is implemented (see https://github.com/TUM-Dev/TUM-Live-Voice-Service), we never got enough GPU capacity to enable the feature. We're actively investigating buying hardware privately. 

This lecture already has subtitles: 
![grafik](https://github.com/user-attachments/assets/fe38a680-bdd2-4391-920e-c89f383a37f0)
https://tum.live/w/cit-gr/26188

**Comment by carlobortolan** [comment] 2024-08-30 20:37
> probably duplicate of #1364 :) Functionality is implemented (see https://github.com/TUM-Dev/TUM-Live-Voice-Service)

Ah sorry for the confusion, besides searching for certain keywords, I was thinking more of a feature that lets you read and scroll through the _entire_ transcript of a lecture.
And while it probably won't be a major feature, I'd guess that it would still be an interesting functionality (especially for those who might be in a hurry and just want to quickly recap / scroll through the content of a certain lecture).

> we never got enough GPU capacity to enable the feature. We're actively investigating buying hardware privately.

iirc, in a recent tumlive meeting, there was the idea of using some unused resources (e.g., the Worker VMs at night or during the semester breaks)  to transcribe past VODs - even if the VMs don't have powerful GPUs, it still should be enough to transcribe VODs. So it might even be that next semester there will be more lecture VODs with subtitles :eyes:

**Comment by CommanderStorm** [comment] 2024-08-31 20:36
> we never got enough GPU capacity

We need to communicate this better in the future. OpenSource@TUM has funding.
I have put a 3090 in "our the usual place".
That should be enough and a big upgrade to the 1660 Super.

With algorithmic improvements like https://github.com/SYSTRAN/faster-whisper I don't see a reason why we could not have semi-realtime transcription if we are smart about this.

@joschahenningsen could you please install the GPU?

**Closed as completed** 2024-12-05 07:01 UTC
Labels: feature :sparkles:, Open Source Lab
