### ISSUE TITLE
session zx6r

### ISSUE THREAD

**Issue by Filip427** [joschahenningsen/TUM-Live#1173] opened 2023-09-28 11:39 UTC
I'm on tum live trying2watch a broadcast.
I click on play and it doesn't work.
the session already beagn, even though there says no active stream and stream is due. 

https://github.com/TUM-Dev/gocast/assets/110301238/329728f4-9748-4f52-be06-aef4cf2f0d80

**Comment by joschahenningsen** [comment] 2023-09-28 11:45
Duplicate of #1174

**Closed as completed by joschahenningsen** 2023-09-28 11:45 UTC
