### ISSUE TITLE
Adding external participants to a course does not work

### ISSUE THREAD

**Issue by maxi-k** [joschahenningsen/TUM-Live#1010] opened 2023-04-26 08:19 UTC
**Describe the bug**
As a course admin, I see an option to add external participants to the course on the admin page by entering a name and an email address.
The input placeholder text indicates that it is possible to add external mail addresses here, and that they should receive an invitation mail.
When I test this with one of my private email addresses, I don't receive an email and there's no indication that anything happened.

**To Reproduce**
1. Go to the admin page of a course you administrate
2. Scroll down to the "External Participants" section
3. Add a name and private email address you know exists (I checked multiple providers)
4. Click "Submit"
5. Check every spam folder, observe no invitation mail exists
6. Klick the "Show Invitations" Link in the "External Participants" section; there are no invitations there either

**Expected behavior**
I expected an invitation mail to arrive at the email account I tested this with, and maybe some kind of data to appear in the 'invitations' section.

**Desktop**
 - OS: Ubuntu 22.10
 - Browser: Firefox
 - Version: 111

**Additional context**
I checked the networking tab using the browser inspection view.
This seems to POST form data to `/api/course/{cousrseId}/createUserForCourse` and always returns 200 OK.

**Comment by karjo24** [comment] 2024-11-14 09:51
I'm not able to reproduce this. @joschahenningsen do you know whether you could repro this at the time of self assigning this or not?

**Comment by karjo24** [comment] 2024-11-14 09:58
Anyways, I'll fix the bug that "show invitation" doesn't actually show anything.

**Comment by joschahenningsen** [comment] 2024-11-14 10:01
I cannot recall, I remember having implemented a new email queuing table https://github.com/TUM-Dev/gocast/blob/f4bf9417cb861123a95f3aab0a7076af82577169/dao/email.go#L18 for inviting admins to their lectures, which works reliably. We should use it also for inviting external participants.

**Comment by karjo24** [comment] 2024-11-14 10:29
> We should use it also for inviting external participants.

You already changed the respective functions so external participants are invited via the email queuing table in June of 2023.

**Closed as completed** 2024-11-26 16:20 UTC
