### ISSUE TITLE
Fullscreen space not used reasonably.

### ISSUE THREAD

**Issue by Infraviored** [joschahenningsen/TUM-Live#604] opened 2022-07-23 19:40 UTC
**Describe the bug**
Fullscreen space not used reasonably.

**To Reproduce**
Use Laptop (with 4K?) display
Klick fullscreen

**Expected behavior**
The whole area should be used. 
Prof window on the right should have the option to not be displayed at all.
If prof. window is visible, the rest of the space should be occupied by the lecture slides.

**Screenshots**
![fullscreen](https://user-images.githubusercontent.com/94627194/180620499-ff20fa49-d2be-47ab-8786-0542e280e94e.png)

**Desktop (please complete the following information):**
Ubuntu 22.04
Chrome Browser
(same issue everywhere)

**Comment by joschahenningsen** [comment] 2022-07-24 07:58
Duplicate of  #418 and possibly fixed in #603 (and follow-ups)

**Closed as completed by joschahenningsen** 2022-07-24 07:58 UTC

**Comment by joschahenningsen** [comment] 2022-07-24 08:06
> Prof window on the right should have the option to not be displayed at all.

Have you tried klicking the buttons below the video? 
![grafik](https://user-images.githubusercontent.com/44805696/180638206-bc2ac9df-e34d-4b0b-ac1e-d4d7b296d168.png)
